### ISSUE TITLE
REQ: cert-manager integration

### ISSUE THREAD

**Issue by cccsss01** [FubarDevelopment/certbot-dns-windows#1]
Thank you! this looks very promising, and chance you have information or could add incorporating this into cert-manager?

**Comment by fubar-coder** [comment]
Hi, I didn't even know cert-manager, but I guess that you mean [https://cert-manager.io/](https://cert-manager.io/)? I don't use it and I don't even know where to start. Maybe you should create an issue on [cert-manager's GitHub repository](https://github.com/cert-manager/cert-manager) instead. They can use the hook itself and/or modify it as needed.
